// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD1yhT-edXYbSAJOZ7NiJoZBqWC-b6Vcs',
    appId: '1:270297500519:web:58efca7be777a64fba3dc2',
    messagingSenderId: '270297500519',
    projectId: 'enkurstaj',
    authDomain: 'enkurstaj.firebaseapp.com',
    storageBucket: 'enkurstaj.firebasestorage.app',
    measurementId: 'G-Z4ZRGMNCK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxM6KDeVZIwWqLkLPouTm1sXhZ3mtHqXQ',
    appId: '1:270297500519:android:4746290bec51080fba3dc2',
    messagingSenderId: '270297500519',
    projectId: 'enkurstaj',
    storageBucket: 'enkurstaj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnt3Qt7ffxCdeKNTnqBqpoZIF6iOOchrk',
    appId: '1:270297500519:ios:b5dff7c006ee6e59ba3dc2',
    messagingSenderId: '270297500519',
    projectId: 'enkurstaj',
    storageBucket: 'enkurstaj.firebasestorage.app',
    iosBundleId: 'com.example.gun4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnt3Qt7ffxCdeKNTnqBqpoZIF6iOOchrk',
    appId: '1:270297500519:ios:b5dff7c006ee6e59ba3dc2',
    messagingSenderId: '270297500519',
    projectId: 'enkurstaj',
    storageBucket: 'enkurstaj.firebasestorage.app',
    iosBundleId: 'com.example.gun4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD1yhT-edXYbSAJOZ7NiJoZBqWC-b6Vcs',
    appId: '1:270297500519:web:d38d68aad2dd27aeba3dc2',
    messagingSenderId: '270297500519',
    projectId: 'enkurstaj',
    authDomain: 'enkurstaj.firebaseapp.com',
    storageBucket: 'enkurstaj.firebasestorage.app',
    measurementId: 'G-JLQLNCB7CY',
  );
}
